default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true

  extensions:
    - .js
    - .jsx
    - .coffee
    - .erb

development:
  <<: *default
  compile: true
  devtool: sourcemaps
  use_reloader?: false
  compile_full_assets: true
  manifest: true
  extract_css: true

  performance:
    hints: false
    maxEntrypointSize: 512000
    maxAssetSize: 512000

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true