source "https://rubygems.org"

gem "bootsnap", ">= 1.4.4", require: false
gem "brakeman", "~> 7.0", require: false
gem "debug", ">= 1.0.0", platforms: %i[mri windows], require: "debug/prelude"
gem "devise", ">= 4.8.0"
gem "importmap-rails", ">= 0.5.0"
gem "jbuilder", ">= 2.11.2"
gem "kamal", ">= 0.1.0", require: false
gem "omniauth-google-oauth2", ">= 0.8.0"
gem "omniauth-facebook", ">= 8.0.0"
# Remova estas linhas do Gemfile
gem "puma", ">= 5.0"
gem "rails", "~> 8.0.1"
gem "rubocop-rails-omakase", ">= 1.0.0", require: false
gem "sprockets-rails", ">= 3.2.2"
gem "solid_cache", ">= 1.0.0"
gem "solid_queue", ">= 1.0.0"
gem "sqlite3", ">= 2.1"
gem "stimulus-rails", ">= 0.5.0"
gem "thruster", ">= 0.1.0", require: false
gem "turbo-rails", ">= 0.9.0"
gem "tzinfo-data", ">= 1.2021.5", platforms: %i[windows jruby]
gem "webpacker", "~> 5.4"  

group :development do
  gem "web-console", ">= 4.1.0"
end

group :test do
  gem "capybara", ">= 3.35.3"
  gem "selenium-webdriver", ">= 4.0.0"
end
gem 'tailwindcss-rails', '~> 2.0.0'
gem 'autoprefixer-rails'
